# Generated by Django 5.2 on 2025-05-03 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0003_smtpconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Business Assistant', max_length=100)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_configs', to='business.business')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('session_key', models.CharField(blank=True, max_length=100, null=True)),
                ('summary', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='business.business')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tool_calls', models.JSONField(blank=True, default=list, null=True)),
                ('tool_call_id', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_agent.chat')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['phone_number'], name='ai_agent_ch_phone_n_9fa95f_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['session_key'], name='ai_agent_ch_session_d00d2c_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['created_at'], name='ai_agent_ch_created_50ec49_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('business', 'phone_number'), ('business', 'session_key')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['created_at'], name='ai_agent_me_created_e0e6cd_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['role'], name='ai_agent_me_role_6ac8fa_idx'),
        ),
    ]
