# Generated by Django 5.1.6 on 2025-08-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customer_user_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='timezone',
            field=models.CharField(default='UTC', max_length=100),
        ),
    ]
