# Generated by Django 5.1.6 on 2025-09-27 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_businesssettings_biweeklydiscount_and_more'),
        ('customer', '0005_customer_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='accounts.business'),
        ),
    ]
