# Generated by Django 5.1.6 on 2025-10-31 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_businesssettings_biweeklydiscount_and_more'),
        ('customer', '0007_alter_customer_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable custom pricing for this customer')),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, help_text='Custom base price (leave blank to use business default)', max_digits=10, null=True)),
                ('bedroom_price', models.DecimalField(blank=True, decimal_places=2, help_text='Custom price per bedroom (leave blank to use business default)', max_digits=10, null=True)),
                ('bathroom_price', models.DecimalField(blank=True, decimal_places=2, help_text='Custom price per bathroom (leave blank to use business default)', max_digits=10, null=True)),
                ('deposit_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Custom deposit fee (leave blank to use business default)', max_digits=10, null=True)),
                ('tax_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Custom tax percentage (leave blank to use business default)', max_digits=5, null=True)),
                ('sqft_multiplier_standard', models.DecimalField(blank=True, decimal_places=2, help_text='Custom square feet multiplier for standard cleaning', max_digits=5, null=True)),
                ('sqft_multiplier_deep', models.DecimalField(blank=True, decimal_places=2, help_text='Custom square feet multiplier for deep cleaning', max_digits=5, null=True)),
                ('sqft_multiplier_moveinout', models.DecimalField(blank=True, decimal_places=2, help_text='Custom square feet multiplier for move-in/out cleaning', max_digits=5, null=True)),
                ('sqft_multiplier_airbnb', models.DecimalField(blank=True, decimal_places=2, help_text='Custom square feet multiplier for Airbnb cleaning', max_digits=5, null=True)),
                ('weekly_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Custom weekly discount percentage', max_digits=5, null=True)),
                ('biweekly_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Custom bi-weekly discount percentage', max_digits=5, null=True)),
                ('monthly_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Custom monthly discount percentage', max_digits=5, null=True)),
                ('addon_price_dishes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('addon_price_laundry', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('addon_price_window', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('addon_price_pets', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('addon_price_fridge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('addon_price_oven', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('addon_price_baseboard', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('addon_price_blinds', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('addon_price_green', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('addon_price_cabinets', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('addon_price_patio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('addon_price_garage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this custom pricing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_pricings', to='accounts.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_pricings', to=settings.AUTH_USER_MODEL)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_pricing', to='customer.customer')),
            ],
            options={
                'verbose_name': 'Customer Pricing',
                'verbose_name_plural': 'Customer Pricings',
                'ordering': ['-created_at'],
                'unique_together': {('customer', 'business')},
            },
        ),
        migrations.CreateModel(
            name='CustomerCustomAddonPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_price', models.DecimalField(decimal_places=2, help_text='Custom price for this addon for this customer', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customaddons')),
                ('customer_pricing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_addon_prices', to='customer.customerpricing')),
            ],
            options={
                'verbose_name': 'Customer Custom Addon Pricing',
                'verbose_name_plural': 'Customer Custom Addon Pricings',
                'ordering': ['custom_addon__addonName'],
                'unique_together': {('customer_pricing', 'custom_addon')},
            },
        ),
    ]
