# Generated by Django 5.1.6 on 2025-11-02 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_businesssettings_biweeklydiscount_and_more'),
        ('customer', '0008_customerpricing_customercustomaddonpricing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='business',
        ),
        migrations.AddField(
            model_name='customer',
            name='businesses',
            field=models.ManyToManyField(blank=True, related_name='customers', to='accounts.business'),
        ),
        migrations.AlterField(
            model_name='customerpricing',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_pricings', to='customer.customer'),
        ),
    ]
