# Generated by Django 5.1.6 on 2025-11-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_remove_customer_business_customer_businesses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpricing',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Enable or disable custom pricing for this customer'),
        ),
    ]
