# Generated by Django 5.1.6 on 2025-04-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='voice_calls',
            new_name='agents',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='leads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='zapier',
            field=models.IntegerField(default=0),
        ),
    ]
