# Generated by Django 5.1.6 on 2025-04-04 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_rename_voice_calls_subscriptionplan_agents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='zapier',
        ),
    ]
