# Generated by Django 5.1.6 on 2025-04-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_coupon_limit_type_couponusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinghistory',
            name='square_invoice_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='billinghistory',
            name='square_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='businesssubscription',
            name='square_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='businesssubscription',
            name='square_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
