# Generated by Django 5.1.6 on 2025-04-07 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0008_feature_subscriptionplan_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='category',
        ),
    ]
