# Generated by Django 5.1.6 on 2025-04-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0010_trialplan_businesssubscription_is_trial_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrialPlan',
        ),
        migrations.RemoveField(
            model_name='businesssubscription',
            name='is_trial',
        ),
        migrations.RemoveField(
            model_name='businesssubscription',
            name='trial_end_date',
        ),
        migrations.AlterField(
            model_name='businesssubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('past_due', 'Past Due'), ('trialing', 'Trialing'), ('ended', 'Ended')], default='active', max_length=20),
        ),
    ]
