# Generated by Django 5.1.6 on 2025-04-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0011_delete_trialplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='cleaners',
            field=models.IntegerField(default=5),
        ),
    ]
