# Generated by Django 5.1.6 on 2025-05-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0012_subscriptionplan_cleaners'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_invite_only',
            field=models.BooleanField(default=False, help_text='If enabled, this plan will only be available to users with a direct link'),
        ),
    ]
