# Generated by Django 5.1.6 on 2025-06-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0013_subscriptionplan_is_invite_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='display_name',
            field=models.CharField(default='', help_text='Name displayed to users', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='plan_tier',
            field=models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise'), ('trial', 'Trial'), ('custom', 'Custom')], default='starter', help_text='The tier of the plan (Starter, Professional, Enterprise, etc.)', max_length=15),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('free', 'Free'), ('paid', 'Paid'), ('trial', 'Trial')], default='paid', max_length=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='slug',
            field=models.SlugField(default='Test', help_text='Unique identifier for the plan, used in URLs and code', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Order in which plans should be displayed (lower numbers first)'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='billing_cycle',
            field=models.CharField(choices=[('14_days', '14 Days'), ('monthly', 'Monthly'), ('2_months', '2 Months'), ('3_months', '3 Months'), ('6_months', '6 Months'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], default='monthly', max_length=10),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(help_text='Internal name for the plan', max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
