# Generated by Django 5.1.6 on 2025-06-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0014_subscriptionplan_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(default='', help_text='Internal name for the plan', max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique identifier for the plan, used in URLs and code', max_length=100, null=True, unique=True),
        ),
    ]
