# Generated by Django 5.1.6 on 2025-06-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0015_alter_subscriptionplan_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique identifier for the plan, used in URLs and code', max_length=100, null=True),
        ),
    ]
