# Generated by Django 5.1.6 on 2025-06-17 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_business_timezone'),
        ('subscription', '0016_alter_subscriptionplan_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetupFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pait_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setup_fee', to='accounts.business')),
            ],
        ),
    ]
