# Generated by Django 5.1.6 on 2025-07-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0018_remove_subscriptionplan_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='setupfee',
            name='call_status',
            field=models.CharField(choices=[('booked', 'Booked'), ('completed', 'Completed'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
