# Generated by Django 5.1.6 on 2025-10-01 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0019_setupfee_call_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssubscription',
            name='new_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_subscriptions', to='subscription.coupon'),
        ),
    ]
