# Generated by Django 5.1.6 on 2025-10-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0020_businesssubscription_new_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='charge_onboarding_fee',
            field=models.BooleanField(default=False),
        ),
    ]
