# Generated by Django 5.1.6 on 2026-01-08 15:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_thumbtackprofile_business_info_last_refresh_and_more'),
        ('subscription', '0021_coupon_charge_onboarding_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionRenewalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('no_card', 'No Card Available'), ('free_plan', 'Free Plan - No Payment Required')], max_length=20)),
                ('renewal_type', models.CharField(choices=[('automatic', 'Automatic Renewal'), ('plan_change', 'Plan Change'), ('upgrade', 'Upgrade'), ('downgrade', 'Downgrade')], default='automatic', max_length=20)),
                ('amount_charged', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('square_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('card_last_4', models.CharField(blank=True, max_length=4, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50, null=True)),
                ('details', models.JSONField(default=dict, help_text='Additional renewal details including payment response, notifications sent, etc.')),
                ('attempted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal_logs', to='subscription.billinghistory')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_logs', to='accounts.business')),
                ('new_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_plan_renewals', to='subscription.subscriptionplan')),
                ('old_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_plan_renewals', to='subscription.subscriptionplan')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal_logs', to='subscription.businesssubscription')),
            ],
            options={
                'ordering': ['-attempted_at'],
                'indexes': [models.Index(fields=['-attempted_at'], name='subscriptio_attempt_a41916_idx'), models.Index(fields=['business', '-attempted_at'], name='subscriptio_busines_a5a68b_idx'), models.Index(fields=['status', '-attempted_at'], name='subscriptio_status_3342f5_idx')],
            },
        ),
    ]
