# Generated by Django 5.1.6 on 2025-09-20 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_business_cleaner_payout_percentage'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('notification', '0003_notification_email_to_delete_notificationpreference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_recipie_417fc4_idx',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='sms_from',
            new_name='sms_to',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='email_attachments',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='email_from',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='email_reply_to',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='status',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('in_app', 'In-App')], max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='accounts.business'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient'], name='notificatio_recipie_33f584_idx'),
        ),
    ]
