# Generated by Django 5.1.6 on 2025-08-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashbaord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='object_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
