# Generated by Django 5.1.6 on 2025-10-22 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashbaord', '0002_alter_activitylog_object_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyPressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keys', models.CharField(max_length=10000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keypress_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Key Press Log',
                'verbose_name_plural': 'Key Press Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
