# Generated by Django 5.1.6 on 2025-10-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashbaord', '0003_keypresslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keypresslog',
            name='keys',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
