# Generated by Django 5.0.7 on 2025-02-19 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.CharField(blank=True, max_length=50, null=True)),
                ('apiKey', models.CharField(blank=True, max_length=255, null=True)),
                ('webhookUrl', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessId', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('businessName', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('bookingIntegrations', models.ManyToManyField(blank=True, related_name='integrated_businesses', to='accounts.bookingintegration')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bookingintegration',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='primary_integration', to='accounts.business'),
        ),
        migrations.CreateModel(
            name='ApiCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retellAPIKey', models.CharField(blank=True, max_length=255, null=True)),
                ('retellWebhookURL', models.URLField(blank=True, null=True)),
                ('voiceAgentNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.business')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedroomPrice', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bathroomPrice', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('depositFee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taxPercent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sqftMultiplierStandard', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sqftMultiplierDeep', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sqftMultiplierMoveinout', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sqftMultiplierAirbnb', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('addonPriceDishes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('addonPriceLaundry', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('addonPriceWindow', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('addonPricePets', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('addonPriceFridge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('addonPriceOven', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('addonPriceBaseboard', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('addonPriceBlinds', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('addonPriceGreen', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('addonPriceCabinets', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('addonPricePatio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('addonPriceGarage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customAddons', models.JSONField(blank=True, default=dict, null=True)),
                ('commercialRequestLink', models.URLField(blank=True, max_length=500, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='accounts.business')),
            ],
            options={
                'verbose_name': 'Business Settings',
                'verbose_name_plural': 'Business Settings',
            },
        ),
    ]
