# Generated by Django 5.0.7 on 2025-02-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicredential',
            name='secretKey',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
