# Generated by Django 5.0.7 on 2025-02-19 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_business_createdat_business_updatedat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesssettings',
            name='customAddons',
        ),
        migrations.CreateModel(
            name='CustomAddons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addonName', models.CharField(blank=True, max_length=255, null=True)),
                ('addonPrice', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_custom_addons', to='accounts.business')),
            ],
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='customAddons',
            field=models.ManyToManyField(blank=True, related_name='business_settings', to='accounts.customaddons'),
        ),
    ]
