# Generated by Django 5.0.7 on 2025-02-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_businesssettings_customaddons_customaddons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customaddons',
            name='addonQty',
            field=models.IntegerField(default=0),
        ),
    ]
