# Generated by Django 5.0.7 on 2025-02-21 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customaddons_addonqty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingintegration',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_integration', to='accounts.business'),
        ),
    ]
