# Generated by Django 5.0.7 on 2025-02-21 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_bookingintegration_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customaddons',
            name='addonQty',
        ),
    ]
