# Generated by Django 5.1.6 on 2025-02-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_customaddons_addonqty'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingintegration',
            name='emailHostPasswrod',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bookingintegration',
            name='emailHostUser',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
