# Generated by Django 5.0.7 on 2025-02-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_bookingintegration_emailhostpasswrod_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingintegration',
            name='emailHostPasswrod',
        ),
        migrations.RemoveField(
            model_name='bookingintegration',
            name='emailHostUser',
        ),
        migrations.AddField(
            model_name='apicredential',
            name='gmail_host_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apicredential',
            name='gmail_host_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
