# Generated by Django 5.0.7 on 2025-02-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_bookingintegration_emailhostpasswrod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customaddons',
            name='addonDataName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
