# Generated by Django 5.1.6 on 2025-03-02 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customaddons_addondataname'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('otp_sent_count', models.IntegerField(default=0)),
                ('is_account_locked', models.BooleanField(default=False)),
                ('lock_expiry', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_otps', to='accounts.business')),
            ],
            options={
                'verbose_name': 'Password Reset OTP',
                'verbose_name_plural': 'Password Reset OTPs',
            },
        ),
    ]
