# Generated by Django 5.1.6 on 2025-03-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_passwordresetotp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='timezone',
            field=models.CharField(blank=True, default='UTC', max_length=50, null=True),
        ),
    ]
