# Generated by Django 5.1.6 on 2025-03-03 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_business_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='timezone',
        ),
    ]
