# Generated by Django 5.1.6 on 2025-03-07 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_business_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apicredential',
            name='gmail_host_password',
        ),
        migrations.RemoveField(
            model_name='apicredential',
            name='gmail_host_user',
        ),
        migrations.CreateModel(
            name='SMTPConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(blank=True, max_length=255, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.business')),
            ],
        ),
    ]
