# Generated by Django 5.1.6 on 2025-03-10 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_apicredential_gmail_host_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicredential',
            name='twilioSmsNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
