# Generated by Django 5.1.6 on 2025-03-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_apicredential_twiliosmsnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicredential',
            name='twilioAccountSid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apicredential',
            name='twilioAuthToken',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apicredential',
            name='twimlAppSid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
