# Generated by Django 5.1.6 on 2025-03-15 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_apicredential_twilioaccountsid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='bookingIntegrations',
        ),
        migrations.DeleteModel(
            name='BookingIntegration',
        ),
    ]
