# Generated by Django 5.1.6 on 2025-03-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_business_bookingintegrations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
    ]
