# Generated by Django 5.1.6 on 2025-03-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_business_isactive_business_isapproved'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpconfig',
            name='from_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smtpconfig',
            name='reply_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
