# Generated by Django 5.1.6 on 2025-03-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_smtpconfig_from_name_smtpconfig_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='useCall',
            field=models.BooleanField(default=False),
        ),
    ]
