# Generated by Django 5.1.6 on 2025-04-02 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_business_timetowait'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apicredential',
            name='retellAPIKey',
        ),
        migrations.RemoveField(
            model_name='apicredential',
            name='retellWebhookURL',
        ),
        migrations.RemoveField(
            model_name='apicredential',
            name='voiceAgentNumber',
        ),
    ]
