# Generated by Django 5.1.6 on 2025-04-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_apicredential_retellapikey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='square_card_id',
            field=models.CharField(blank=True, help_text='Square payment card ID for recurring payments', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='square_customer_id',
            field=models.CharField(blank=True, help_text='Square customer ID for recurring payments', max_length=255, null=True),
        ),
    ]
