# Generated by Django 5.1.6 on 2025-04-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_business_isrejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='auto_upgrade',
            field=models.BooleanField(default=False, help_text='Automatically upgrade to next plan when usage exceeds limits'),
        ),
    ]
