# Generated by Django 5.1.6 on 2025-04-11 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_squarecredentials'),
        ('automation', '0020_lead_follow_up_call_sent_lead_follow_up_call_sent_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaner_profiles', to='accounts.business')),
                ('cleaner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='automation.cleaners')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cleaner_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
