# Generated by Django 5.1.6 on 2025-04-22 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_cleanerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPalCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('paypal_secret_key', models.CharField(blank=True, max_length=255, null=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_credentials', to='accounts.business')),
            ],
        ),
        migrations.CreateModel(
            name='StripeCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_secret_key', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_publishable_key', models.CharField(blank=True, max_length=255, null=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_credentials', to='accounts.business')),
            ],
        ),
    ]
