# Generated by Django 5.1.6 on 2025-04-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_paypalcredentials_stripecredentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='defaultPaymentMethod',
            field=models.CharField(blank=True, choices=[('square', 'Square'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], help_text='Default payment method for collecting payments', max_length=255, null=True),
        ),
    ]
