# Generated by Django 5.1.6 on 2025-05-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_business_defaultpaymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='cleaner_pay_percentage',
            field=models.IntegerField(default=25),
        ),
    ]
