# Generated by Django 5.1.6 on 2025-05-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_business_cleaner_pay_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='job_assignment',
            field=models.CharField(blank=True, choices=[('high_rated', 'High Rated'), ('all_available', 'All Available')], default='all_available', help_text='Job assignment method', max_length=255, null=True),
        ),
    ]
