# Generated by Django 5.1.6 on 2025-06-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_business_job_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='timezone',
            field=models.CharField(default='UTC', help_text="Business timezone (e.g., 'America/New_York', 'Europe/London')", max_length=50),
        ),
    ]
