# Generated by Django 5.1.6 on 2025-06-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_thumbtackprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbtackprofile',
            name='access_token',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='thumbtackprofile',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
