# Generated by Django 5.1.6 on 2025-07-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_alter_thumbtackprofile_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='job_assignment',
            field=models.CharField(blank=True, choices=[('high_rated', 'Auto-assign by points rating'), ('all_available', 'Send Job to available cleaners')], default='all_available', help_text='Job assignment method', max_length=255, null=True),
        ),
    ]
