# Generated by Django 5.1.6 on 2025-07-01 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_alter_business_job_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='cleaner_pay_percentage',
        ),
    ]
