# Generated by Django 5.1.6 on 2025-08-29 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_remove_business_cleaner_pay_percentage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SMTPConfig',
        ),
    ]
