# Generated by Django 5.1.6 on 2025-08-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_delete_smtpconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base price for cleaning service', max_digits=10),
        ),
        migrations.AlterField(
            model_name='businesssettings',
            name='bathroomPrice',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price per bathroom', max_digits=10),
        ),
        migrations.AlterField(
            model_name='businesssettings',
            name='bedroomPrice',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price per bedroom', max_digits=10),
        ),
        migrations.AlterField(
            model_name='businesssettings',
            name='depositFee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Deposit fee', max_digits=10),
        ),
        migrations.AlterField(
            model_name='businesssettings',
            name='sqftMultiplierDeep',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Square feet multiplier for deep cleaning', max_digits=5),
        ),
        migrations.AlterField(
            model_name='businesssettings',
            name='sqftMultiplierMoveinout',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Square feet multiplier for move-in/out cleaning', max_digits=5),
        ),
        migrations.AlterField(
            model_name='businesssettings',
            name='sqftMultiplierStandard',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Square feet multiplier for standard cleaning', max_digits=5),
        ),
        migrations.AlterField(
            model_name='businesssettings',
            name='taxPercent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tax percentage', max_digits=5),
        ),
    ]
