# Generated by Django 5.1.6 on 2025-09-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_businesssettings_base_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='cleaner_payout_percentage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
