# Generated by Django 5.1.6 on 2025-09-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_business_cleaner_payout_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='biweeklyDiscount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Bi-weekly discount', max_digits=5),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='monthlyDiscount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly discount', max_digits=5),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='weeklyDiscount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Weekly discount', max_digits=5),
        ),
    ]
