# Generated by Django 5.1.6 on 2025-11-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_businesssettings_biweeklydiscount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='allow_partial_payment',
            field=models.BooleanField(default=True, help_text='Allow customers to make partial payments on invoices'),
        ),
        migrations.AddField(
            model_name='business',
            name='minimum_partial_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Minimum amount required for partial payment', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='businesssettings',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Base price for cleaning service (optional)', max_digits=10, null=True),
        ),
    ]
