# Generated by Django 5.1.6 on 2026-01-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_business_allow_partial_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbtackprofile',
            name='business_info_last_refresh',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thumbtackprofile',
            name='cached_business_info',
            field=models.JSONField(blank=True, help_text='Cached business information from Thumbtack', null=True),
        ),
        migrations.AddField(
            model_name='thumbtackprofile',
            name='cached_user_info',
            field=models.JSONField(blank=True, help_text='Cached user information from Thumbtack', null=True),
        ),
        migrations.AddField(
            model_name='thumbtackprofile',
            name='cached_webhooks',
            field=models.JSONField(blank=True, help_text='Cached webhooks from Thumbtack', null=True),
        ),
        migrations.AddField(
            model_name='thumbtackprofile',
            name='user_info_last_refresh',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thumbtackprofile',
            name='webhooks_last_refresh',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
