# Generated by Django 5.1.6 on 2025-06-30 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_alter_thumbtackprofile_access_token_and_more'),
        ('saas', '0002_platformsettings_setup_fee_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platformsettings',
            options={'verbose_name': 'Platform Settings', 'verbose_name_plural': 'Platform Settings'},
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='company_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='company_email',
            field=models.EmailField(default='support@cleaningbiz.ai', max_length=254),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='company_name',
            field=models.CharField(default='CleaningBiz AI', max_length=100),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='company_phone',
            field=models.CharField(default='+1-800-123-4567', max_length=20),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='default_timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='maintenance_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='maintenance_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='support_email',
            field=models.EmailField(default='support@cleaningbiz.ai', max_length=254),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('bug', 'Bug Report'), ('feature', 'Feature Request'), ('support', 'Support Request'), ('billing', 'Billing Issue'), ('other', 'Other')], default='bug', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('browser_info', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='ticket_screenshots/')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.business')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support Ticket',
                'verbose_name_plural': 'Support Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='ticket_attachments/')),
                ('is_internal', models.BooleanField(default=False, help_text='Internal notes visible only to staff')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='saas.supportticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
