# Generated by Django 5.1.6 on 2025-12-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0003_alter_platformsettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='square_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='square_app_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='square_environment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='square_location_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
