# Generated by Django 5.2.1 on 2026-04-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0004_platformsettings_square_access_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoLeads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Demo Lead',
                'verbose_name_plural': 'Demo Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
