# Generated by Django 5.1.6 on 2025-04-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retell_agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retellagent',
            name='agent_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
