# Generated by Django 5.1.6 on 2025-02-27 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_customaddons_addondataname'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_url', models.URLField(help_text='Base URL for the API endpoint')),
                ('auth_type', models.CharField(choices=[('api_key', 'API Key'), ('oauth2', 'OAuth 2.0'), ('basic', 'Basic Auth'), ('none', 'No Authentication')], default='none', max_length=20)),
                ('auth_data', models.JSONField(blank=True, help_text='Authentication credentials', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='accounts.business')),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], max_length=20)),
                ('request_data', models.JSONField()),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='integrations.platformintegration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_field', models.CharField(help_text='Field name from your system', max_length=100)),
                ('target_field', models.CharField(help_text='Field name expected by the platform', max_length=100)),
                ('field_type', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('boolean', 'Boolean'), ('array', 'Array'), ('object', 'Object'), ('date', 'Date')], default='string', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('default_value', models.CharField(blank=True, max_length=255, null=True)),
                ('transformation_rule', models.JSONField(blank=True, help_text='Optional transformation logic', null=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='integrations.platformintegration')),
            ],
        ),
    ]
