# Generated by Django 5.1.6 on 2025-02-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datamapping',
            options={'ordering': ['parent_object', 'order']},
        ),
        migrations.AddField(
            model_name='datamapping',
            name='order',
            field=models.IntegerField(default=0, help_text='Order within the parent object'),
        ),
        migrations.AddField(
            model_name='datamapping',
            name='parent_object',
            field=models.CharField(blank=True, help_text='Parent object name for nested fields', max_length=100, null=True),
        ),
    ]
