# Generated by Django 5.1.6 on 2025-02-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_platformintegration_data_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformintegration',
            name='auth_type',
            field=models.CharField(choices=[('none', 'No Authentication'), ('token', 'Token Authentication'), ('basic', 'Basic Authentication')], default='none', max_length=20),
        ),
    ]
