# Generated by Django 5.1.6 on 2025-02-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_alter_platformintegration_auth_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datamapping',
            options={'ordering': ['parent_path', 'order']},
        ),
        migrations.RemoveField(
            model_name='datamapping',
            name='parent_object',
        ),
        migrations.AddField(
            model_name='datamapping',
            name='parent_path',
            field=models.CharField(blank=True, help_text='Dot-separated path for nested fields (e.g., customer.address)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datamapping',
            name='field_type',
            field=models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('boolean', 'Boolean'), ('array', 'Array'), ('object', 'Object'), ('date', 'Date')], default='string', max_length=50),
        ),
        migrations.AlterField(
            model_name='datamapping',
            name='source_field',
            field=models.CharField(help_text='Field name from your system', max_length=255),
        ),
        migrations.AlterField(
            model_name='datamapping',
            name='target_field',
            field=models.CharField(help_text='Field name expected by the platform', max_length=255),
        ),
        migrations.AlterField(
            model_name='platformintegration',
            name='auth_data',
            field=models.JSONField(blank=True, default=dict, help_text='Authentication credentials'),
        ),
        migrations.AlterField(
            model_name='platformintegration',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
