# Generated by Django 5.1.6 on 2025-02-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_alter_datamapping_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformintegration',
            name='data_format',
        ),
        migrations.AlterField(
            model_name='datamapping',
            name='field_type',
            field=models.CharField(choices=[('string', 'Text'), ('number', 'Number'), ('boolean', 'True/False'), ('date', 'Date'), ('time', 'Time'), ('datetime', 'Date & Time'), ('array', 'Array/List'), ('object', 'Object')], default='string', max_length=50),
        ),
    ]
