# Generated by Django 5.1.6 on 2025-02-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_remove_platformintegration_data_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformintegration',
            name='platform_type',
            field=models.CharField(choices=[('direct_api', 'Direct API Integration'), ('workflow', 'Workflow Automation Platform')], default='direct_api', max_length=20),
        ),
        migrations.AddField(
            model_name='platformintegration',
            name='webhook_url',
            field=models.URLField(blank=True, help_text='Webhook URL for workflow platforms', null=True),
        ),
        migrations.AlterField(
            model_name='platformintegration',
            name='base_url',
            field=models.URLField(blank=True, help_text='Base URL for the API endpoint', null=True),
        ),
    ]
