# Generated by Django 5.1.6 on 2025-07-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_remove_datamapping_transformation_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformintegration',
            name='headers',
            field=models.JSONField(blank=True, default=dict, help_text='HTTP headers to include with API requests'),
        ),
    ]
