# Generated by Django 5.1.6 on 2025-07-08 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0009_platformintegration_headers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformintegration',
            name='auth_data',
        ),
        migrations.RemoveField(
            model_name='platformintegration',
            name='auth_type',
        ),
    ]
