# Generated by Django 5.0.7 on 2025-01-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('session_id', models.PositiveIntegerField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('uri', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
            ],
        ),
    ]
