# Generated by Django 5.0.7 on 2025-02-15 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0005_appointment_duration_appointment_endtime_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
