# Generated by Django 5.0.7 on 2025-02-19 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0007_lead_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Credentials',
        ),
    ]
