# Generated by Django 5.1.6 on 2025-02-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0010_cleaners_cleaneravailability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaneravailability',
            name='dayOfWeek',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10),
        ),
    ]
