# Generated by Django 5.1.6 on 2025-02-26 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0011_alter_cleaneravailability_dayofweek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaneravailability',
            name='cleaner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.cleaners'),
        ),
    ]
