# Generated by Django 5.1.6 on 2025-02-26 13:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0012_alter_cleaneravailability_cleaner'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaneravailability',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cleaneravailability',
            name='offDay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cleaneravailability',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
