# Generated by Django 5.1.6 on 2025-02-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0013_cleaneravailability_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaneravailability',
            name='endTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cleaneravailability',
            name='startTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
