# Generated by Django 5.1.6 on 2025-02-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0014_alter_cleaneravailability_endtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaners',
            name='isAvailable',
            field=models.BooleanField(default=True),
        ),
    ]
