# Generated by Django 5.1.6 on 2025-03-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0016_remove_cleaners_bookings'),
        ('bookings', '0007_remove_payment_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaneravailability',
            name='availability_type',
            field=models.CharField(choices=[('weekly', 'Weekly Recurring'), ('specific', 'Specific Date')], default='weekly', max_length=10),
        ),
        migrations.AddField(
            model_name='cleaneravailability',
            name='specific_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cleaners',
            name='bookings',
            field=models.ManyToManyField(blank=True, related_name='cleaners', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='cleaneravailability',
            name='dayOfWeek',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='cleaneravailability',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('availability_type', 'weekly'), ('dayOfWeek__isnull', False), ('specific_date__isnull', True)), models.Q(('availability_type', 'specific'), ('dayOfWeek__isnull', True), ('specific_date__isnull', False)), _connector='OR'), name='valid_availability_type_fields'),
        ),
    ]
