# Generated by Django 5.1.6 on 2025-03-10 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0017_cleaneravailability_availability_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='emailSentAt',
            new_name='call_sent_at',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='isConverted',
            new_name='is_call_sent',
        ),
        migrations.AddField(
            model_name='lead',
            name='is_response_received',
            field=models.BooleanField(default=False),
        ),
    ]
