# Generated by Django 5.1.6 on 2025-03-17 21:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0018_rename_emailsentat_lead_call_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaners',
            name='rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
