# Generated by Django 5.1.6 on 2025-05-16 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0022_lead_bathrooms_lead_bedrooms_lead_squarefeet_and_more'),
        ('bookings', '0011_booking_daybeforeremindersentat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenJob',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='pending', max_length=255)),
                ('assignment_type', models.CharField(choices=[('top_rated', 'Top Rated'), ('all_available', 'All Available')], default='all_available', max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking')),
                ('cleaner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.cleaners')),
            ],
        ),
    ]
