# Generated by Django 5.1.6 on 2025-05-16 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_business_cleaner_pay_percentage'),
        ('automation', '0023_openjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openjob',
            name='cleaner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.cleanerprofile'),
        ),
    ]
