# Generated by Django 5.1.6 on 2025-08-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0024_alter_openjob_cleaner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
