# Generated by Django 5.1.6 on 2025-09-24 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0025_alter_lead_phone_number'),
        ('bookings', '0019_booking_arrived_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingNotificationTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(default='cleaner_assignment_check', max_length=50)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking')),
            ],
            options={
                'unique_together': {('booking', 'notification_type')},
            },
        ),
    ]
