# Generated by Django 5.1.6 on 2025-11-07 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_business_allow_partial_payment_and_more'),
        ('automation', '0026_bookingnotificationtracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='call_error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='call_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='call_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('initiated', 'Initiated'), ('completed', 'Completed'), ('failed', 'Failed'), ('not_attempted', 'Not Attempted')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='follow_up_call_error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='follow_up_call_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('initiated', 'Initiated'), ('completed', 'Completed'), ('failed', 'Failed'), ('not_attempted', 'Not Attempted')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='notification_method',
            field=models.CharField(blank=True, choices=[('sms', 'SMS'), ('call', 'Call'), ('both', 'Both'), ('none', 'None')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='sms_error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='sms_message_sid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='sms_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='sms_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='sms_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('not_attempted', 'Not Attempted')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('sms', 'SMS'), ('call', 'Call'), ('follow_up_call', 'Follow-up Call')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('initiated', 'Initiated'), ('completed', 'Completed'), ('failed', 'Failed'), ('not_attempted', 'Not Attempted')], default='pending', max_length=20)),
                ('attempt_number', models.IntegerField(default=1)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('message_sid', models.CharField(blank=True, max_length=255, null=True)),
                ('call_id', models.CharField(blank=True, max_length=255, null=True)),
                ('message_content', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.business')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='automation.lead')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lead', 'notification_type'], name='automation__lead_id_ed5e41_idx'), models.Index(fields=['business', 'created_at'], name='automation__busines_82bcab_idx'), models.Index(fields=['status'], name='automation__status_0dcf11_idx')],
            },
        ),
    ]
