# Generated by Django 5.1.6 on 2025-12-17 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_business_allow_partial_payment_and_more'),
        ('automation', '0027_lead_call_error_message_lead_call_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadsWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_source', models.CharField(choices=[('thumbtack', 'Thumbtack'), ('manual_webhook', 'Manual Webhook')], default='manual_webhook', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('webhook_data', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.business')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'created_at'], name='automation__busines_b2e3f0_idx'), models.Index(fields=['status'], name='automation__status_b9c24a_idx')],
            },
        ),
    ]
