# Generated by Django 5.1.6 on 2025-03-10 09:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='is_first_message',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='message',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='role',
        ),
        migrations.AddField(
            model_name='chat',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('message', models.TextField()),
                ('is_first_message', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_agent.chat')),
            ],
        ),
    ]
