# Generated by Django 5.1.6 on 2025-03-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0002_remove_chat_is_first_message_remove_chat_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='summary',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
