# Generated by Django 5.1.6 on 2025-03-10 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_apicredential_gmail_host_password_and_more'),
        ('ai_agent', '0003_chat_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(default='Sarah', max_length=50)),
                ('agent_role', models.CharField(default='virtual customer support and sales representative', max_length=100)),
                ('business_description', models.TextField(blank=True, help_text='Description of the business that will be used in the AI prompt', null=True)),
                ('business_mission', models.TextField(blank=True, help_text='Mission statement points, will be formatted as bullet points', null=True)),
                ('services', models.JSONField(blank=True, default=dict, help_text='JSON object containing service types and their descriptions', null=True)),
                ('business_hours', models.CharField(default='All Weekdays from 9:00 AM - 5:00 PM', help_text='Business hours in text format', max_length=255)),
                ('timezone', models.CharField(default='America/Chicago', max_length=50)),
                ('custom_instructions', models.TextField(blank=True, help_text='Any additional custom instructions for the AI agent', null=True)),
                ('default_deep_cleaning_surcharge', models.CharField(default='20%', help_text='Surcharge for deep cleaning as percentage or fixed amount', max_length=20)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_config', to='accounts.business')),
            ],
            options={
                'verbose_name': 'AI Agent Configuration',
                'verbose_name_plural': 'AI Agent Configurations',
            },
        ),
    ]
