# Generated by Django 5.1.6 on 2025-03-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0004_agentconfiguration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentconfiguration',
            name='business_hours',
        ),
        migrations.RemoveField(
            model_name='agentconfiguration',
            name='default_deep_cleaning_surcharge',
        ),
        migrations.RemoveField(
            model_name='agentconfiguration',
            name='timezone',
        ),
        migrations.AlterField(
            model_name='agentconfiguration',
            name='services',
            field=models.TextField(blank=True, help_text='Services provided by the business, will be formatted as bullet points', null=True),
        ),
    ]
