# Generated by Django 5.1.6 on 2025-03-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0005_remove_agentconfiguration_business_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfiguration',
            name='script',
            field=models.TextField(blank=True, help_text='Script for the AI agent', null=True),
        ),
    ]
