# Generated by Django 5.1.6 on 2025-03-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0006_agentconfiguration_script'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='chatId',
        ),
        migrations.AddField(
            model_name='chat',
            name='clientInterest',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='clientName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='clientPhoneNumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
