# Generated by Django 5.1.6 on 2025-03-10 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0007_remove_chat_chatid_chat_clientinterest_and_more'),
        ('automation', '0018_rename_emailsentat_lead_call_sent_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='clientInterest',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='clientName',
        ),
        migrations.AddField(
            model_name='chat',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='automation.lead'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='clientPhoneNumber',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
