# Generated by Django 5.1.6 on 2025-03-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0008_remove_chat_clientinterest_remove_chat_clientname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('tool', 'Tool')], max_length=20),
        ),
    ]
