# Generated by Django 5.1.6 on 2025-03-15 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0009_alter_messages_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentconfiguration',
            old_name='script',
            new_name='prompt',
        ),
        migrations.RemoveField(
            model_name='agentconfiguration',
            name='agent_name',
        ),
        migrations.RemoveField(
            model_name='agentconfiguration',
            name='agent_role',
        ),
        migrations.RemoveField(
            model_name='agentconfiguration',
            name='business_description',
        ),
        migrations.RemoveField(
            model_name='agentconfiguration',
            name='business_mission',
        ),
        migrations.RemoveField(
            model_name='agentconfiguration',
            name='custom_instructions',
        ),
        migrations.RemoveField(
            model_name='agentconfiguration',
            name='services',
        ),
    ]
