# Generated by Django 5.1.6 on 2025-03-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0010_rename_script_agentconfiguration_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='sessionKey',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
