# Generated by Django 5.1.6 on 2025-03-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0011_chat_sessionkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfiguration',
            name='agent_name',
            field=models.CharField(blank=True, default='Sarah', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('not_interested', 'Not Interested'), ('booked', 'Booked')], default='pending', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
