# Generated by Django 5.1.6 on 2025-03-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0012_agentconfiguration_agent_name_chat_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('not_interested', 'Not Interested'), ('booked', 'Booked'), ('call_sent', 'Call Sent')], max_length=20),
        ),
    ]
