# Generated by Django 5.1.6 on 2025-04-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0013_alter_chat_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('not_interested', 'Not Interested'), ('booked', 'Booked'), ('call_sent', 'Call Sent'), ('follow_up_call_sent', 'Follow Up Call Sent')], max_length=20),
        ),
    ]
