# Generated by Django 5.1.6 on 2025-08-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0014_alter_chat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='mode',
            field=models.CharField(choices=[('live', 'Live'), ('test', 'Test')], default='live', max_length=10),
        ),
    ]
