# Generated by Django 5.1.6 on 2025-09-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0015_messages_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='clientPhoneNumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
