# Generated by Django 5.1.6 on 2025-11-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0016_alter_chat_clientphonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentconfiguration',
            name='prompt',
        ),
        migrations.AddField(
            model_name='agentconfiguration',
            name='custom_instructions',
            field=models.TextField(blank=True, help_text='Custom instructions for the AI agent', null=True),
        ),
        migrations.AddField(
            model_name='agentconfiguration',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
