# Generated by Django 5.0.7 on 2025-02-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='serviceType',
            field=models.CharField(blank=True, choices=[('regularCleaning', 'Regular Cleaning'), ('deepCleaning', 'Deep Cleaning'), ('commercialCleaning', 'Commercial Cleaning')], max_length=50, null=True),
        ),
    ]
