# Generated by Django 5.0.7 on 2025-02-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_businesssettings_customaddons_customaddons_and_more'),
        ('bookings', '0003_remove_booking_address_remove_booking_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='addonCustom1',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='addonCustom2',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='addonCustom3',
        ),
        migrations.AddField(
            model_name='booking',
            name='customAddons',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='accounts.customaddons'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='serviceType',
            field=models.CharField(blank=True, choices=[('standard', 'Standard Cleaning'), ('deep', 'Deep Cleaning'), ('moveinmoveout', 'Move In/Move Out'), ('airbnb', 'Airbnb Cleaning')], max_length=50, null=True),
        ),
    ]
