# Generated by Django 5.0.7 on 2025-02-21 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_customaddons_addonqty'),
        ('bookings', '0004_remove_booking_addoncustom1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='recurring',
            field=models.CharField(choices=[('one-time', 'One Time'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly')], default='one-time', max_length=20),
        ),
        migrations.CreateModel(
            name='BookingCustomAddons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customaddons')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_addons', to='bookings.booking')),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='customAddons',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='bookings.bookingcustomaddons'),
        ),
    ]
