# Generated by Django 5.0.7 on 2025-02-21 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_recurring_bookingcustomaddons_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingcustomaddons',
            name='booking',
        ),
    ]
