# Generated by Django 5.1.6 on 2025-02-26 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0010_cleaners_cleaneravailability'),
        ('bookings', '0006_remove_bookingcustomaddons_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cleaningDateTime',
        ),
        migrations.AddField(
            model_name='booking',
            name='cleaner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automation.cleaners'),
        ),
        migrations.AddField(
            model_name='booking',
            name='cleaningDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='endTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='startTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
