# Generated by Django 5.1.6 on 2025-04-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_booking_paymentremindersentat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='serviceType',
            field=models.CharField(blank=True, choices=[('standard', 'Standard Cleaning'), ('deep', 'Deep Cleaning'), ('moveinmoveout', 'Move In/Move Out'), ('airbnb', 'Airbnb Cleaning'), ('commercial', 'Commercial Cleaning')], max_length=50, null=True),
        ),
    ]
