# Generated by Django 5.1.6 on 2025-04-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_booking_cancelled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dayBeforeReminderSentAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='hourBeforeReminderSentAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
