# Generated by Django 5.1.6 on 2025-05-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_booking_daybeforeremindersentat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='arrival_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
