# Generated by Django 5.1.6 on 2025-08-29 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_cleanerpayout'),
        ('customer', '0002_customer_address_customer_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='city',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='companyName',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='stateOrProvince',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='zipCode',
        ),
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer'),
        ),
    ]
