# Generated by Django 5.1.6 on 2025-09-02 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_booking_address1_booking_address2_booking_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='city',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='stateOrProvince',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='zipCode',
        ),
    ]
