# Generated by Django 5.1.6 on 2025-09-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_remove_booking_address1_remove_booking_address2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tip',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
