# Generated by Django 5.1.6 on 2025-09-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_booking_tip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bathrooms',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bedrooms',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='booking',
            name='squareFeet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
