# Generated by Django 5.1.6 on 2025-09-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_alter_booking_bathrooms_alter_booking_bedrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
