# Generated by Django 5.1.6 on 2025-09-24 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_booking_arrived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='last_recurring_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='next_recurring_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='parent_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_bookings', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='booking',
            name='postServiceFollowupSentAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
