# Generated by Django 5.1.6 on 2025-09-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0021_booking_cancelled_reason_booking_rescheduled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='appliedDiscountPercent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Applied discount percentage for recurring bookings', max_digits=5),
        ),
        migrations.AddField(
            model_name='booking',
            name='discountAmount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount amount in dollars', max_digits=10),
        ),
    ]
