# Generated by Django 5.1.6 on 2025-10-31 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0022_booking_applieddiscountpercent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pricing_snapshot',
            field=models.JSONField(blank=True, help_text='Snapshot of pricing used at booking time', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='used_custom_pricing',
            field=models.BooleanField(default=False, help_text='Whether custom customer pricing was used for this booking'),
        ),
    ]
