# Generated by Django 5.1.6 on 2025-11-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0023_booking_pricing_snapshot_booking_used_custom_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='key_location',
            field=models.CharField(blank=True, help_text='Key code or location where key is hidden', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='will_someone_be_home',
            field=models.BooleanField(default=False, help_text='Will someone be home during the cleaning?'),
        ),
    ]
