# Generated by Django 5.1.6 on 2025-11-07 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_business_allow_partial_payment_and_more'),
        ('bookings', '0024_booking_key_location_booking_will_someone_be_home'),
        ('customer', '0010_alter_customerpricing_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique coupon code (e.g., SUMMER2024)', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Internal description of the coupon', null=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage (0-100) or fixed amount', max_digits=10)),
                ('max_uses', models.IntegerField(blank=True, help_text='Maximum number of times this coupon can be used (null = unlimited)', null=True)),
                ('max_uses_per_customer', models.IntegerField(default=1, help_text='Maximum uses per customer')),
                ('current_uses', models.IntegerField(default=0, help_text='Current number of times used')),
                ('valid_from', models.DateTimeField(help_text='Coupon becomes valid from this date/time')),
                ('valid_until', models.DateTimeField(help_text='Coupon expires after this date/time')),
                ('min_booking_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum booking amount required to use this coupon', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the coupon is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='accounts.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usage', to='bookings.booking')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='bookings.coupon')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to='customer.customer')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code', 'business'], name='bookings_co_code_97e9a1_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['status', 'is_active'], name='bookings_co_status_ce5e8b_idx'),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['coupon', 'customer'], name='bookings_co_coupon__c6593c_idx'),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['applied_at'], name='bookings_co_applied_88e4de_idx'),
        ),
    ]
