# Generated by Django 5.1.6 on 2025-11-07 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0025_coupon_couponusage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='applied_coupon',
            field=models.ForeignKey(blank=True, help_text='Coupon applied to this booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.coupon'),
        ),
        migrations.AddField(
            model_name='booking',
            name='coupon_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount amount from coupon', max_digits=10),
        ),
    ]
