# Generated by Django 5.1.6 on 2025-03-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_rename_stripechargeid_payment_squarepaymentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='squarePaymentId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
