# Generated by Django 5.1.6 on 2025-03-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transactionId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
