# Generated by Django 5.1.6 on 2025-09-06 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_payment_fromaccountnumber_payment_frombankname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_paid_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('partial', 'Partial Payment'), ('full', 'Full Payment'), ('authorized', 'Authorized Payment')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invoice.invoice'),
        ),
    ]
