# Generated by Django 5.1.6 on 2025-09-10 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_invoice_total_paid_amount_payment_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-createdAt']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-createdAt']},
        ),
    ]
